cpu: false

gpu_ids:
  - 0

data:
  src: fr
  tgt: en
  dir: data/wmt_fr_en
  batch_size: 16
  max_length: 70

encoder:
  embedding_dim: 128
  embedding_dropout: 0.2

decoder:
  embedding_dim: 128
  embedding_dropout: 0.2
  prediction_dropout: 0.2
 
network:
  bias: false
  block_sizes:
    - 24
  division_factor: 2
  dropout: 0.2
  efficient: true
  growth_rate: 32

optim: 
  seed: 1
  lr: 0.005
  epochs: 35
  beta1: 0.9
  beta2: 0.999
  wd: 0.001
