model_name: densenet-l12
default_config : config/default.yaml

gpu_ids:
  - 0

network:
  block_sizes:
    - 12

data:
  batch_size: 24
  max_length: 50

optim: 
  seed: 3
  lr: 0.0015
  max_epochs: 40
