model_name: news_fr_en
default_config : config/default.yaml

cpu: false

gpu_ids:
  - 0

network:
  efficient: false
  type: pervasive-original
  block_sizes:
    - 6
    - 4

data:
  src: fr
  tgt: en
  dir: data/news_fr_en
  batch_size: 24
  epoch_size: 60000
  loader: standard
  max_val_size: 240
  max_length: 80
  vocab: vocab.txt

optim: 
  seed: 3
  lr: 0.01
  epochs: 20
  beta1: 0.9
  beta2: 0.999
  wd: 0.001
