model_name: progressive-5
default_config : config/default.yaml

network:
  type: pervasive-bert
  block_sizes:
    - 12

data:
  src: fr
  tgt: en
  dir: data/bert_fr_en
  batch_size: 32
  epoch_size: 16384
  loader: standard
  max_val_size: 256
  max_test_size: 256
  max_length: 50
  vocab: vocab.txt

optim: 
  seed: 3
  lr: 0.002
  epochs: 24
